import type { ColorSchemeId, ColorSchemeDef, VisualStyleId } from '@/types'

export const colorSchemes: Record<ColorSchemeId, ColorSchemeDef> = {
  // ===== Geometric (existing 7) =====
  mint: {
    id: 'mint',
    name: 'Mint Cream',
    nameZh: '薄荷奶油',
    visualStyle: 'geometric',
    colors: {
      bg: '#F7FAF8',
      bgAlt: '#EEF5F0',
      surface: '#FFFFFF',
      surfaceHover: '#F0F7F3',
      text: '#2C3E35',
      textSecondary: '#5A7D6C',
      textMuted: '#8FA89D',
      primary: '#7EB8A0',
      primaryHover: '#5A9B7F',
      accent: '#C4956B',
      accentHover: '#A87A52',
      cursorColor: '#4A8C6F',
      border: '#D4E5DB',
      borderLight: '#E8F2EC',
      glow: 'rgba(126, 184, 160, 0.15)',
      glowSecondary: 'rgba(196, 149, 107, 0.1)',
    },
  },
  rose: {
    id: 'rose',
    name: 'Dusty Rose',
    nameZh: '复古玫瑰',
    visualStyle: 'geometric',
    colors: {
      bg: '#FBF7F7',
      bgAlt: '#F5EEEE',
      surface: '#FFFFFF',
      surfaceHover: '#F8F2F2',
      text: '#3E2C2E',
      textSecondary: '#7D5A5E',
      textMuted: '#A88A8E',
      primary: '#C49595',
      primaryHover: '#A87A7A',
      accent: '#8FA88D',
      accentHover: '#6B8A68',
      cursorColor: '#8B4A5A',
      border: '#E8D4D5',
      borderLight: '#F2E4E5',
      glow: 'rgba(196, 149, 149, 0.15)',
      glowSecondary: 'rgba(143, 168, 141, 0.1)',
    },
  },
  lavender: {
    id: 'lavender',
    name: 'Lavender Mist',
    nameZh: '薰衣草雾',
    visualStyle: 'geometric',
    colors: {
      bg: '#F9F7FB',
      bgAlt: '#F2EEF5',
      surface: '#FFFFFF',
      surfaceHover: '#F5F2F8',
      text: '#2E2C3E',
      textSecondary: '#5E5A7D',
      textMuted: '#8E8AA8',
      primary: '#9B8EC4',
      primaryHover: '#7B6BA8',
      accent: '#C4956B',
      accentHover: '#A87A52',
      cursorColor: '#6B5BA0',
      border: '#E0D4E8',
      borderLight: '#EDE4F2',
      glow: 'rgba(155, 142, 196, 0.15)',
      glowSecondary: 'rgba(196, 149, 107, 0.1)',
    },
  },
  sand: {
    id: 'sand',
    name: 'Warm Sand',
    nameZh: '暖沙色',
    visualStyle: 'geometric',
    colors: {
      bg: '#FBF9F7',
      bgAlt: '#F5F0EB',
      surface: '#FFFFFF',
      surfaceHover: '#F7F3EE',
      text: '#3E352C',
      textSecondary: '#7D6A5A',
      textMuted: '#A8927D',
      primary: '#C4A87E',
      primaryHover: '#A88B5A',
      accent: '#7E9BC4',
      accentHover: '#5A7BA8',
      cursorColor: '#8B6B4A',
      border: '#E8DCCB',
      borderLight: '#F2EBDE',
      glow: 'rgba(196, 168, 126, 0.15)',
      glowSecondary: 'rgba(126, 155, 196, 0.1)',
    },
  },
  sage: {
    id: 'sage',
    name: 'Sage Green',
    nameZh: '鼠尾草绿',
    visualStyle: 'geometric',
    colors: {
      bg: '#F8F9F7',
      bgAlt: '#F0F3EE',
      surface: '#FFFFFF',
      surfaceHover: '#F4F6F2',
      text: '#2E352D',
      textSecondary: '#5A6B58',
      textMuted: '#8A9888',
      primary: '#8FA88D',
      primaryHover: '#6B8A68',
      accent: '#A88DA0',
      accentHover: '#8A6B82',
      cursorColor: '#4A6B4A',
      border: '#D8E0D5',
      borderLight: '#E8EDE5',
      glow: 'rgba(143, 168, 141, 0.15)',
      glowSecondary: 'rgba(168, 141, 160, 0.1)',
    },
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean Haze',
    nameZh: '海洋薄雾',
    visualStyle: 'geometric',
    colors: {
      bg: '#F7F9FA',
      bgAlt: '#EEF2F5',
      surface: '#FFFFFF',
      surfaceHover: '#F2F5F8',
      text: '#2C353E',
      textSecondary: '#5A6B7D',
      textMuted: '#8A9BA8',
      primary: '#8EB4C4',
      primaryHover: '#6B96A8',
      accent: '#C4A87E',
      accentHover: '#A88B5A',
      cursorColor: '#4A6B8B',
      border: '#D4DEE5',
      borderLight: '#E5EBF0',
      glow: 'rgba(142, 180, 196, 0.15)',
      glowSecondary: 'rgba(196, 168, 126, 0.1)',
    },
  },
  noir: {
    id: 'noir',
    name: 'Noir Ink',
    nameZh: '墨夜',
    visualStyle: 'geometric',
    colors: {
      bg: '#0F1117',
      bgAlt: '#161922',
      surface: '#1C1F2B',
      surfaceHover: '#232738',
      text: '#E4E6EF',
      textSecondary: '#9BA0B8',
      textMuted: '#686D80',
      primary: '#8BA4C4',
      primaryHover: '#A8BED8',
      accent: '#C4A47E',
      accentHover: '#D4B892',
      cursorColor: '#B8C8E0',
      border: '#2A2D3A',
      borderLight: '#222536',
      glow: 'rgba(139, 164, 196, 0.12)',
      glowSecondary: 'rgba(196, 164, 126, 0.08)',
    },
  },

  // ===== Neo-Brutalism =====
  'brutal-light': {
    id: 'brutal-light',
    name: 'Brutal Light',
    nameZh: '粗野·奶白',
    visualStyle: 'brutalist',
    colors: {
      bg: '#FFFDF5',
      bgAlt: '#F5F0E0',
      surface: '#FFFFFF',
      surfaceHover: '#FFEB3B',
      text: '#000000',
      textSecondary: '#333333',
      textMuted: '#666666',
      primary: '#FF3366',
      primaryHover: '#E02050',
      accent: '#FFD93D',
      accentHover: '#E5C020',
      cursorColor: '#000000',
      border: '#000000',
      borderLight: '#333333',
      glow: 'rgba(255, 51, 102, 0.2)',
      glowSecondary: 'rgba(255, 217, 61, 0.2)',
    },
  },
  'brutal-dark': {
    id: 'brutal-dark',
    name: 'Brutal Dark',
    nameZh: '粗野·暗夜',
    visualStyle: 'brutalist',
    colors: {
      bg: '#1A1A2E',
      bgAlt: '#16213E',
      surface: '#0F0F1A',
      surfaceHover: '#252545',
      text: '#FFFFFF',
      textSecondary: '#CCCCCC',
      textMuted: '#999999',
      primary: '#FF3366',
      primaryHover: '#FF5588',
      accent: '#6BCB77',
      accentHover: '#8DE099',
      cursorColor: '#FFFFFF',
      border: '#FFFFFF',
      borderLight: '#CCCCCC',
      glow: 'rgba(255, 51, 102, 0.3)',
      glowSecondary: 'rgba(107, 203, 119, 0.2)',
    },
  },

  // ===== Retro-Futurism =====
  'retro-sunset': {
    id: 'retro-sunset',
    name: 'Retro Sunset',
    nameZh: '复古·日落',
    visualStyle: 'retro-futurism',
    colors: {
      bg: '#0D0221',
      bgAlt: '#1A0B2E',
      surface: 'rgba(26, 11, 46, 0.7)',
      surfaceHover: 'rgba(45, 20, 70, 0.8)',
      text: '#E8E8FF',
      textSecondary: '#B8B8D0',
      textMuted: '#8080A0',
      primary: '#FF6B9D',
      primaryHover: '#FF8DB5',
      accent: '#FFAA00',
      accentHover: '#FFCC44',
      cursorColor: '#00D4FF',
      border: '#FF6B9D',
      borderLight: '#C77DFF',
      glow: 'rgba(255, 107, 157, 0.4)',
      glowSecondary: 'rgba(199, 125, 255, 0.3)',
    },
  },
  'retro-neon': {
    id: 'retro-neon',
    name: 'Retro Neon',
    nameZh: '复古·霓虹',
    visualStyle: 'retro-futurism',
    colors: {
      bg: '#0A0A1A',
      bgAlt: '#12122A',
      surface: 'rgba(10, 10, 30, 0.75)',
      surfaceHover: 'rgba(20, 20, 50, 0.85)',
      text: '#E0E8FF',
      textSecondary: '#A0B0D0',
      textMuted: '#6878A0',
      primary: '#00D4FF',
      primaryHover: '#44E8FF',
      accent: '#C77DFF',
      accentHover: '#DDAAFF',
      cursorColor: '#00D4FF',
      border: '#00D4FF',
      borderLight: '#C77DFF',
      glow: 'rgba(0, 212, 255, 0.4)',
      glowSecondary: 'rgba(199, 125, 255, 0.3)',
    },
  },
}

export const schemeList: ColorSchemeId[] = [
  'mint', 'rose', 'lavender', 'sand', 'sage', 'ocean', 'noir',
  'brutal-light', 'brutal-dark',
  'retro-sunset', 'retro-neon',
]

export function getSchemesForStyle(style: VisualStyleId): ColorSchemeId[] {
  return Object.values(colorSchemes)
    .filter((s) => s.visualStyle === style)
    .map((s) => s.id)
}
